name: example
version: 0.1.0.0
github: "githubuser/example"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2023 Author name here"

extra-source-files:
  - README.org
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/example#readme>

dependencies:
  - base >= 4.7 && < 5
  - servant
  - servant-server
  - servant-client
  - text
  - wai
  - warp
  - aeson
  - http-types
  - vector
  - http-client
  - exceptions
  - wai-extra
  - data-default
  - stm
  - containers
  - time
  - mtl
  - cassava
  - conduit
  - csv-conduit
  - http-conduit
  - bytestring
  - wreq
  - lens
  - pretty-simple
  - optparse-applicative
  - http-client-tls
  - async

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  api:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - example

tests:
  example-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - hspec-discover
      - hspec-junit-formatter
      - example

default-extensions:
  - DeriveGeneric
  - ImportQualifiedPost
  - OverloadedStrings
  - LambdaCase
  - GeneralizedNewtypeDeriving
  - NamedFieldPuns
